name: what_url_ci
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
jobs:
  tests:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Tests
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno test